quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/grupal-db
quarkus.datasource.username=postgres
quarkus.datasource.password=Aucas1945
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# Flyway: las tablas las crea app-authors
quarkus.flyway.migrate-at-start=false

# Stork: descubrimiento de app-authors via Consul
quarkus.stork.authors-api.service-discovery.type=consul
quarkus.stork.authors-api.service-discovery.consul-host=${consul.host}
quarkus.stork.authors-api.service-discovery.consul-port=${consul.port}
quarkus.stork.authors-api.service-discovery.application=app-authors
quarkus.stork.authors-api.service-discovery.refresh-period=5s
quarkus.stork.authors-api.load-balancer.type=round-robin

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Health + metricas
quarkus.smallrye-health.root-path=/q/health
quarkus.micrometer.export.prometheus.path=/q/metrics

# Container image
quarkus.container-image.group=byronsda45
quarkus.container-image.name=app-books
quarkus.container-image.tag=latest