CREATE TABLE IF NOT EXISTS customers
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(255),
    address    VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uq_customers_email UNIQUE (email)
    );

INSERT INTO customers (first_name, last_name, email, phone, address, created_at)
SELECT * FROM (VALUES
                   ('Ana', 'Gomez', 'ana.gomez@uce.edu.ec', '0991234567', 'Av. America N12-34', NOW()),
                   ('Carlos', 'Morales', 'carlos.morales@uce.edu.ec', '0987654321', 'Av. 6 de Diciembre N45-67', NOW()),
                   ('Lucia', 'Rodriguez', 'lucia.rodriguez@uce.edu.ec', '0995556677', 'Av. Colon N89-12', NOW()),
                   ('Diego', 'Salazar', 'diego.salazar@uce.edu.ec', '0998887766', 'Av. Naciones Unidas N23-45', NOW()),
                   ('Maria', 'Ponce', 'maria.ponce@uce.edu.ec', '0993334455', 'Av. Shyris N56-78', NOW())
              ) AS nuevos (first_name, last_name, email, phone, address, created_at)
WHERE NOT EXISTS (SELECT 1 FROM customers);