apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: books-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'app-authors'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: [ 'app-authors:8080' ]
      - job_name: 'app-books'
        metrics_path: '/q/metrics'
        static_configs:
          - targets: [ 'app-books:8080' ]
      - job_name: 'app-customers'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'app-customers:8080' ]