CREATE TABLE authors
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

insert into authors (name) values ('Jorge Icaza');
insert into authors (name) values ('Juan León Mera');
insert into authors (name) values ('José de la Cuadra');
insert into authors (name) values ('Joaquín Gallegos Lara');